# Generated by Django 2.1.5 on 2019-03-15 12:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MylistGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=100, unique=True)),
                ('genre_img', models.ImageField(default='default.gif', upload_to='profile_pics')),
                ('genre_slug', models.SlugField(allow_unicode=True, blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='MylistProduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_name', models.CharField(max_length=200, unique=True)),
                ('production_info', models.TextField()),
                ('production_img', models.ImageField(default='default.gif', upload_to='profile_pics')),
                ('production_slug', models.SlugField(allow_unicode=True, blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Productions',
            },
        ),
        migrations.CreateModel(
            name='MylistQuarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MylistTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('summary', models.TextField()),
                ('title_img', models.ImageField(default='default.gif', upload_to='profile_pics')),
                ('title_slug', models.SlugField(allow_unicode=True, blank=True, unique=True)),
                ('viewcount', models.IntegerField(default=0)),
                ('userlikes', models.IntegerField(default=0)),
                ('userdislikes', models.IntegerField(default=0)),
                ('genre', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='mylist.MylistGenre', verbose_name='Genres')),
                ('production', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='mylist.MylistProduction', verbose_name='Productions')),
                ('quarter', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='mylist.MylistQuarter', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
            ],
        ),
        migrations.CreateModel(
            name='MylistYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('year_slug', models.SlugField(allow_unicode=True, blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Years',
            },
        ),
        migrations.AddField(
            model_name='mylisttitle',
            name='year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='mylist.MylistYear', verbose_name='Years'),
        ),
    ]
