# Generated by Django 2.1.5 on 2019-03-19 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mylisttitle',
            old_name='genre',
            new_name='genre1',
        ),
        migrations.AddField(
            model_name='mylisttitle',
            name='genre2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genre2', to='mylist.MylistGenre', verbose_name='Genres'),
        ),
        migrations.AddField(
            model_name='mylisttitle',
            name='genre3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genre3', to='mylist.MylistGenre', verbose_name='Genres'),
        ),
    ]
