# Generated by Django 2.1.5 on 2019-03-19 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0002_auto_20190319_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylisttitle',
            name='genre2',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genre2', to='mylist.MylistGenre', verbose_name='Genres'),
        ),
        migrations.AlterField(
            model_name='mylisttitle',
            name='genre3',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genre3', to='mylist.MylistGenre', verbose_name='Genres'),
        ),
    ]
