# Generated by Django 2.1.5 on 2019-04-05 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0003_auto_20190319_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='mylistyear',
            name='production_img',
            field=models.ImageField(default='default.gif', upload_to='productions'),
        ),
        migrations.AlterField(
            model_name='mylistgenre',
            name='genre_img',
            field=models.ImageField(default='default.gif', upload_to='genres'),
        ),
        migrations.AlterField(
            model_name='mylistproduction',
            name='production_img',
            field=models.ImageField(default='default.gif', upload_to='productions'),
        ),
        migrations.AlterField(
            model_name='mylisttitle',
            name='genre2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genre2', to='mylist.MylistGenre', verbose_name='Genres'),
        ),
        migrations.AlterField(
            model_name='mylisttitle',
            name='genre3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genre3', to='mylist.MylistGenre', verbose_name='Genres'),
        ),
        migrations.AlterField(
            model_name='mylisttitle',
            name='title_img',
            field=models.ImageField(default='default.gif', upload_to='titles'),
        ),
    ]
